Scrapper dhl
cuenca-mx/dhlmex-python pull request #1
Opened 2020-01-02 14:06 UTC by agarrido19

Create guides and select on DHL form to be ready to print

2020-01-15 11:56 UTC, ricardo8990 requested changes

2020-01-15 11:56 UTC, ricardo8990 commented on dhlmex/__init__.py
> +        raise httpe
Para qué te sirve cachar una excepción que inmediatamente después vuelves a lanzar?

2020-01-15 11:56 UTC, ricardo8990 commented on dhlmex/__init__.py
> +def get_guides_data(client: Client) -> Dict:
Es mejor crear un `Resource` con todas estas funciones que tenerlas en el archivo `.__init__`, puedes ver como tenemos en: https://github.com/cuenca-mx/stpmex-python/tree/master/stpmex/resources

2020-01-15 11:56 UTC, ricardo8990 commented on .travis.yml
> +  - make format
Travis no debería de hacer cambios al código, solo validar que el formato este correcto

2020-01-15 11:56 UTC, ricardo8990 commented on .coveralls.yml
> +repo_token: l567fVDFDWAxjZmHmHg9jMDKPSYlEA3KV
Esto es para repositorios privados, pero este es público

2020-01-15 18:02 UTC, agarrido19 commented on .coveralls.yml
> +repo_token: l567fVDFDWAxjZmHmHg9jMDKPSYlEA3KV
Ya lo quite

2020-01-15 18:02 UTC, agarrido19 commented on .travis.yml
> +  - make format
Tambien ya lo quite

2020-01-15 18:03 UTC, agarrido19 commented on dhlmex/__init__.py
> +        raise httpe
Creo que lo puse para debug, cuando no pasaba ese request, lo quito

2020-01-16 20:57 UTC, ricardo8990 approved these changes

2020-01-16 21:05 UTC, merged